<?php

namespace ContainerFHlB9pu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3czLlVCService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3czLlVC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3czLlVC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'soutient' => ['privates', '.errored..service_locator.3czLlVC.App\\Entity\\Soutient', NULL, 'Cannot autowire service ".service_locator.3czLlVC": it needs an instance of "App\\Entity\\Soutient" but this type has been excluded because it\'s a Doctrine entity.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'soutient' => 'App\\Entity\\Soutient',
            'entityManager' => '?',
        ]);
    }
}
