<?php

namespace ContainerFHlB9pu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D9Qk__KService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.D9Qk..k' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.D9Qk..k'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategorieController::index' => ['privates', '.service_locator.4CyveaC.App\\Controller\\CategorieController::index()', 'getCategorieControllerindexService', true],
            'App\\Controller\\CategorieController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CategorieController::new()', 'getCategorieControllernewService', true],
            'App\\Controller\\CategorieController::show' => ['privates', '.service_locator.z9d.XgN.App\\Controller\\CategorieController::show()', 'getCategorieControllershowService', true],
            'App\\Controller\\CategorieController::edit' => ['privates', '.service_locator.i9YOweH.App\\Controller\\CategorieController::edit()', 'getCategorieControllereditService', true],
            'App\\Controller\\CategorieController::delete' => ['privates', '.service_locator.i9YOweH.App\\Controller\\CategorieController::delete()', 'getCategorieControllerdeleteService', true],
            'App\\Controller\\RevendicationController::index' => ['privates', '.service_locator.pM0Lsp1.App\\Controller\\RevendicationController::index()', 'getRevendicationControllerindexService', true],
            'App\\Controller\\RevendicationController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\RevendicationController::new()', 'getRevendicationControllernewService', true],
            'App\\Controller\\RevendicationController::show' => ['privates', '.service_locator.p4YOBha.App\\Controller\\RevendicationController::show()', 'getRevendicationControllershowService', true],
            'App\\Controller\\RevendicationController::edit' => ['privates', '.service_locator.t7oLwVi.App\\Controller\\RevendicationController::edit()', 'getRevendicationControllereditService', true],
            'App\\Controller\\RevendicationController::delete' => ['privates', '.service_locator.t7oLwVi.App\\Controller\\RevendicationController::delete()', 'getRevendicationControllerdeleteService', true],
            'App\\Controller\\SoutientController::index' => ['privates', '.service_locator.JEve_QP.App\\Controller\\SoutientController::index()', 'getSoutientControllerindexService', true],
            'App\\Controller\\SoutientController::new' => ['privates', '.service_locator.egipcEH.App\\Controller\\SoutientController::new()', 'getSoutientControllernewService', true],
            'App\\Controller\\SoutientController::show' => ['privates', '.service_locator.9iQPcyN.App\\Controller\\SoutientController::show()', 'getSoutientControllershowService', true],
            'App\\Controller\\SoutientController::edit' => ['privates', '.service_locator.3czLlVC.App\\Controller\\SoutientController::edit()', 'getSoutientControllereditService', true],
            'App\\Controller\\SoutientController::delete' => ['privates', '.service_locator.3czLlVC.App\\Controller\\SoutientController::delete()', 'getSoutientControllerdeleteService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CategorieController:index' => ['privates', '.service_locator.4CyveaC.App\\Controller\\CategorieController::index()', 'getCategorieControllerindexService', true],
            'App\\Controller\\CategorieController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\CategorieController::new()', 'getCategorieControllernewService', true],
            'App\\Controller\\CategorieController:show' => ['privates', '.service_locator.z9d.XgN.App\\Controller\\CategorieController::show()', 'getCategorieControllershowService', true],
            'App\\Controller\\CategorieController:edit' => ['privates', '.service_locator.i9YOweH.App\\Controller\\CategorieController::edit()', 'getCategorieControllereditService', true],
            'App\\Controller\\CategorieController:delete' => ['privates', '.service_locator.i9YOweH.App\\Controller\\CategorieController::delete()', 'getCategorieControllerdeleteService', true],
            'App\\Controller\\RevendicationController:index' => ['privates', '.service_locator.pM0Lsp1.App\\Controller\\RevendicationController::index()', 'getRevendicationControllerindexService', true],
            'App\\Controller\\RevendicationController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\RevendicationController::new()', 'getRevendicationControllernewService', true],
            'App\\Controller\\RevendicationController:show' => ['privates', '.service_locator.p4YOBha.App\\Controller\\RevendicationController::show()', 'getRevendicationControllershowService', true],
            'App\\Controller\\RevendicationController:edit' => ['privates', '.service_locator.t7oLwVi.App\\Controller\\RevendicationController::edit()', 'getRevendicationControllereditService', true],
            'App\\Controller\\RevendicationController:delete' => ['privates', '.service_locator.t7oLwVi.App\\Controller\\RevendicationController::delete()', 'getRevendicationControllerdeleteService', true],
            'App\\Controller\\SoutientController:index' => ['privates', '.service_locator.JEve_QP.App\\Controller\\SoutientController::index()', 'getSoutientControllerindexService', true],
            'App\\Controller\\SoutientController:new' => ['privates', '.service_locator.egipcEH.App\\Controller\\SoutientController::new()', 'getSoutientControllernewService', true],
            'App\\Controller\\SoutientController:show' => ['privates', '.service_locator.9iQPcyN.App\\Controller\\SoutientController::show()', 'getSoutientControllershowService', true],
            'App\\Controller\\SoutientController:edit' => ['privates', '.service_locator.3czLlVC.App\\Controller\\SoutientController::edit()', 'getSoutientControllereditService', true],
            'App\\Controller\\SoutientController:delete' => ['privates', '.service_locator.3czLlVC.App\\Controller\\SoutientController::delete()', 'getSoutientControllerdeleteService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CategorieController::index' => '?',
            'App\\Controller\\CategorieController::new' => '?',
            'App\\Controller\\CategorieController::show' => '?',
            'App\\Controller\\CategorieController::edit' => '?',
            'App\\Controller\\CategorieController::delete' => '?',
            'App\\Controller\\RevendicationController::index' => '?',
            'App\\Controller\\RevendicationController::new' => '?',
            'App\\Controller\\RevendicationController::show' => '?',
            'App\\Controller\\RevendicationController::edit' => '?',
            'App\\Controller\\RevendicationController::delete' => '?',
            'App\\Controller\\SoutientController::index' => '?',
            'App\\Controller\\SoutientController::new' => '?',
            'App\\Controller\\SoutientController::show' => '?',
            'App\\Controller\\SoutientController::edit' => '?',
            'App\\Controller\\SoutientController::delete' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CategorieController:index' => '?',
            'App\\Controller\\CategorieController:new' => '?',
            'App\\Controller\\CategorieController:show' => '?',
            'App\\Controller\\CategorieController:edit' => '?',
            'App\\Controller\\CategorieController:delete' => '?',
            'App\\Controller\\RevendicationController:index' => '?',
            'App\\Controller\\RevendicationController:new' => '?',
            'App\\Controller\\RevendicationController:show' => '?',
            'App\\Controller\\RevendicationController:edit' => '?',
            'App\\Controller\\RevendicationController:delete' => '?',
            'App\\Controller\\SoutientController:index' => '?',
            'App\\Controller\\SoutientController:new' => '?',
            'App\\Controller\\SoutientController:show' => '?',
            'App\\Controller\\SoutientController:edit' => '?',
            'App\\Controller\\SoutientController:delete' => '?',
        ]);
    }
}
