<?php

namespace ContainerFHlB9pu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevendicationControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t7oLwVi.App\Controller\RevendicationController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.t7oLwVi.App\\Controller\\RevendicationController::delete()'] = ($container->privates['.service_locator.t7oLwVi'] ?? $container->load('get_ServiceLocator_T7oLwViService'))->withContext('App\\Controller\\RevendicationController::delete()', $container);
    }
}
