<?php

namespace ContainerFHlB9pu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevendicationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pM0Lsp1.App\Controller\RevendicationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.pM0Lsp1.App\\Controller\\RevendicationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'revendicationRepository' => ['privates', 'App\\Repository\\RevendicationRepository', 'getRevendicationRepositoryService', true],
        ], [
            'revendicationRepository' => 'App\\Repository\\RevendicationRepository',
        ]))->withContext('App\\Controller\\RevendicationController::index()', $container);
    }
}
