<?php

namespace ContainerFHlB9pu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSoutientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3czLlVC.App\Entity\Soutient' shared service.
     *
     * @return \App\Entity\Soutient
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3czLlVC": it needs an instance of "App\\Entity\\Soutient" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
