<?php

namespace ContainerFHlB9pu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSoutientControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9iQPcyN.App\Controller\SoutientController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9iQPcyN.App\\Controller\\SoutientController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'soutient' => ['privates', '.errored..service_locator.9iQPcyN.App\\Entity\\Soutient', NULL, 'Cannot autowire service ".service_locator.9iQPcyN": it needs an instance of "App\\Entity\\Soutient" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'soutient' => 'App\\Entity\\Soutient',
        ]))->withContext('App\\Controller\\SoutientController::show()', $container);
    }
}
