<?php

namespace ContainerTFwXosa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHomeControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.TR5rhg4.App\Controller\HomeController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.TR5rhg4.App\\Controller\\HomeController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'revendicationRepo' => ['privates', 'App\\Repository\\RevendicationRepository', 'getRevendicationRepositoryService', true],
            'categorieRepo' => ['privates', 'App\\Repository\\CategorieRepository', 'getCategorieRepositoryService', true],
        ], [
            'revendicationRepo' => 'App\\Repository\\RevendicationRepository',
            'categorieRepo' => 'App\\Repository\\CategorieRepository',
        ]))->withContext('App\\Controller\\HomeController::index()', $container);
    }
}
