<?php

namespace ContainerTFwXosa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevendicationControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.p4YOBha.App\Controller\RevendicationController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.p4YOBha.App\\Controller\\RevendicationController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'revendication' => ['privates', '.errored..service_locator.p4YOBha.App\\Entity\\Revendication', NULL, 'Cannot autowire service ".service_locator.p4YOBha": it needs an instance of "App\\Entity\\Revendication" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'revendication' => 'App\\Entity\\Revendication',
        ]))->withContext('App\\Controller\\RevendicationController::show()', $container);
    }
}
