<?php

namespace ContainerTFwXosa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevendicationControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.t7oLwVi.App\Controller\RevendicationController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.t7oLwVi'] ?? $container->load('get_ServiceLocator_T7oLwViService'));

        if (isset($container->privates['.service_locator.t7oLwVi.App\\Controller\\RevendicationController::edit()'])) {
            return $container->privates['.service_locator.t7oLwVi.App\\Controller\\RevendicationController::edit()'];
        }

        return $container->privates['.service_locator.t7oLwVi.App\\Controller\\RevendicationController::edit()'] = $a->withContext('App\\Controller\\RevendicationController::edit()', $container);
    }
}
