<?php

namespace ContainerTFwXosa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRevendicationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.p4YOBha.App\Entity\Revendication' shared service.
     *
     * @return \App\Entity\Revendication
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.p4YOBha": it needs an instance of "App\\Entity\\Revendication" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
