<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTFwXosa\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTFwXosa/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTFwXosa.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTFwXosa\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTFwXosa\App_KernelDevDebugContainer([
    'container.build_hash' => 'TFwXosa',
    'container.build_id' => 'e3ea9741',
    'container.build_time' => 1759760210,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTFwXosa');
